compliance-watcher/__tests__/lib/watcher.test.js
compliance-watcher/lib/watcher.js

Added ready checks for watcher

---

compliance-watcher/__mocks__/initialJobNoEnv.js
compliance-watcher/__mocks__/nextJob.js
compliance-watcher/__tests__/lib/watcher.test.js
compliance-watcher/lib/watcher.js
compliance-watcher/package-lock.json
compliance-watcher/package.json

Added release tagging

---

compliance-ui/components/Collapsible.js
compliance-ui/components/Details.js
compliance-ui/components/Grid.js
compliance-ui/components/ReleaseBox.js
compliance-ui/components/status/IsReady.js
compliance-ui/pages/index.js
compliance-ui/pages/singleRelease.js
compliance-ui/util/index.js

- Media Queries for mobile view on index page
- A couple small fixes to the grid and release box

Index mobile

---

compliance-ui/components/Grid.js

- Putting both conditional statements in the `verifications` map only worked by coincidence in the other case for `checks2`
- Separating the failed and passed conditionals at a level higher `controls` seemed to solve this

Fixed data sorting

---

compliance-ui/pages/pdf-singlerelease.js
compliance-ui/pages/pdf-singlerelease2.js

- PDF was not sorting before due to the way the data was being chunked
- Data is being mapped in this new order and pushed into a new sortedData array
- Control Box is now using this sortedData instead of the raw data
- Key values need to be added to cancel out the warning messages currently present

PDF Single Release Sorting 

---

compliance-ui/components/BackToTopButton.js
compliance-ui/components/Details.js

- Since in an earlier PR we had begun sorting the controls by release, I realised it made more sense to have these controls sort by failed controls, like on the other pages.
- Failed controls will now show up at the top of each release list.
| Before | After |
|--------|-------|
|   <img width="1392" alt="screen shot 2019-01-28 at 11 05 42" src="https://user-images.githubusercontent.com/30609058/51849024-d30d4800-22ec-11e9-8b83-7486ede5e2dc.png">     |   <img width="1392" alt="screen shot 2019-01-28 at 11 06 14" src="https://user-images.githubusercontent.com/30609058/51849011-cab50d00-22ec-11e9-9cbe-9c4bf2498f2a.png">  |

Detail sorting

---

compliance-ui/components/Collapsible.js

Quick fix to toggle button width

Quick update

---

pdf-report/src/__tests__/lib/fetchRelease.test.ts
pdf-report/src/__tests__/lib/generateReport.test.ts

Added an additional tests for PDF creation

---

api/package.json
api/yarn.lock

Removed husky from API

---

.github/main.workflow

Adds CI per branch and a notifier

---

runner/package.json
runner/src/__tests__/lib/executeWebhook.test.ts
runner/src/lib/executeWebhook.ts
runner/src/lib/runJobs.ts
runner/yarn.lock

This allows you to specify a webhook callback that is POSTed to when you complete a run. Closes #68

Added execute webhook callback feature

---

web-report/.env.example
web-report/src/__tests__/__page_tests__/details-page.test.js
web-report/src/__tests__/__page_tests__/index-page.test.js
web-report/src/__tests__/__page_tests__/single-release-page.test.js
web-report/src/components/ActionBar.js
web-report/src/components/Header.js
web-report/src/components/Layout.js
web-report/src/components/PrintButton.js
web-report/src/config.js
web-report/src/pages/ReleasePage.js
web-report/src/server.js

Added PDF link in if PDF_REPORT_URL is defined

---

pdf-report/.env.example
pdf-report/src/index.ts

Empty route in subdir now show latest

---

api/cloudbuild.yaml
notifier/cloudbuild.yaml
pdf-report/cloudbuild.yaml
performance-index/cloudbuild.yaml
runner/cloudbuild.yaml
web-report/cloudbuild.yaml

Added continous delivery to cloudbuild

---

elenchos.json
review-manifests/api-deployment.yaml
review-manifests/api-service.yaml
review-manifests/app-deployment.yaml
review-manifests/app-service.yaml
review-manifests/checks-claim.yaml
review-manifests/cluster-role-binding.yaml
review-manifests/cluster-role.yaml
review-manifests/kustomization.yaml
review-manifests/mongo-claim.yaml
review-manifests/mongo-deployment.yaml
review-manifests/mongo-service.yaml
review-manifests/namespace.yaml
review-manifests/pdf-report-deployment.yaml
review-manifests/pdf-report-service.yaml
review-manifests/performance-index-deployment.yaml
review-manifests/performance-index-service.yaml
review-manifests/runner-deployment.yaml
review-manifests/runner-service.yaml
review-manifests/traefik-ingress-controller-cluster-role-binding.yaml
review-manifests/traefik-ingress-controller-cluster-role.yaml
review-manifests/traefik-ingress-controller-deployment.yaml
review-manifests/traefik-ingress-controller-service-account.yaml
review-manifests/traefik-ingress-service.yaml
review-manifests/traefik-ingress.yaml
review-manifests/web-report-deployment.yaml
review-manifests/web-report-service.yaml
web-report/package.json

k8s review

---

web-report/src/components/Header.js
web-report/src/components/PrintButton.js

Separate back to top functionality from print button

---

api/src/db/getFiles.ts
api/src/db/save.ts
api/src/utils/renameFile.ts
api/src/watcher/index.ts

Add a .processed extension to the end of json files once they have been processed.
Closes #104

Rename .json files after being processed

---

performance-index/src/Home.js

Added absolute risk chart

---

review-manifests/web-report-deployment.yaml
web-report/.env.example
web-report/src/__mocks__/mockDataSingleRelease.js
web-report/src/__tests__/__component_tests__/header.test.js
web-report/src/__tests__/__component_tests__/layout.test.js
web-report/src/__tests__/__page_tests__/details-page.test.js
web-report/src/__tests__/__page_tests__/index-page.test.js
web-report/src/__tests__/__page_tests__/single-release-page.test.js
web-report/src/components/Header.js
web-report/src/config.js
web-report/src/pages/ReleasePage.js

Added external link function

---

performance-index/src/client.js
web-report/src/components/Details.js
web-report/src/components/Grid.js

Fixes #108  and other small console errors.

Small console error fixes

---

web-report/src/components/PrintButton.js

Removes PDF link on control page

---

docs/writing-a-check.md

We need a guide on how to write a check.
Note: We don't want this documentation to get out of date very often so referencing back to the other "source(s) of truth" where possible.  
https://github.com/cds-snc/security-goals/blob/writing-a-check/docs/writing-a-check.md

WIP - Document how to write a check

---

runner/src/lib/runJobs.ts

Trying to get more information on #116

Runner error logging

---

README.md

Closes https://github.com/cds-snc/security-goals/issues/96

Update README to include a link to writing a check document

---

web-report/src/LanguageContext.js
web-report/src/client.js
web-report/src/components/ActionBar.js
web-report/src/components/Header.js
web-report/src/components/I18N.js
web-report/src/components/LanguageToggle.js
web-report/src/components/index.js
web-report/src/i18n/translations.json

Adds I18N + Language toggle components.
Uses React Context + React Hooks
Usage:
```<I18N t="tagline" />```
Where tagline is the "key" in the translation JSON file
```json
{
"current-language": {
"en": "English",
"fr": "Français"
},
"tagline": {
"en": "Are we meeting our security goals?",
"fr": "Sommes-nous en train d'atteindre nos objectifs de sécurité?"
}
}
```
https://github.com/cds-snc/security-goals/issues/133

Language toggle

---

web-report/src/__tests__/__component_tests__/home.test.js
web-report/src/components/BackToTopButton.js
web-report/src/components/Collapsible.js
web-report/src/components/Details.js
web-report/src/components/Grid.js
web-report/src/components/Home.js
web-report/src/components/I18N.js
web-report/src/components/PrintButton.js
web-report/src/components/ReleaseBox.js
web-report/src/components/controlbox/Header.js
web-report/src/components/status/Count.js
web-report/src/components/status/PassFailText.js
web-report/src/i18n/translations.json
web-report/src/pages/ReleasePage.js

Updated components to pull text from the translation file.

Web Report - i18n

---

notifier/.env.example
notifier/package.json
notifier/src/index.ts
notifier/src/lib/sendEmail.ts
notifier/yarn.lock

Added Emailer to notifier

---

review-manifests/web-report-deployment.yaml
web-report/.env.example
web-report/src/__tests__/__component_tests__/release-box.test.js
web-report/src/components/Details.js
web-report/src/components/Grid.js
web-report/src/components/Header.js
web-report/src/components/Home.js
web-report/src/components/ReleaseBox.js
web-report/src/config.js
web-report/src/i18n/translations.json

Closes #145 and also partially #140

Adjusted release name

---

notifier/.env.example
notifier/src/lib/notifySlack.ts
notifier/src/lib/sendEmail.ts
performance-index/.env.example
performance-index/src/components/Header.js
performance-index/src/config.js

Added remaining APP NAME envs

---

web-report/.env.example
web-report/src/components/ActionBar.js
web-report/src/config.js
web-report/src/i18n/translations.json

Adds performance index link to the header.
Will add a link back in a separate PR once https://github.com/cds-snc/security-goals/pull/149 gets merged.

Header update

---

performance-index/.env.example
performance-index/package.json
performance-index/src/components/Header.js
performance-index/src/config.js
performance-index/src/i18n/translations.json

Link to web report

---

web-report/src/i18n/translations.json

Merging in Elises translations for the UI

Translations for UI elements
